#!/bin/sh

# $1 - restok.conf path
# $2 - package name
fn_if_package_aegised() {
	if [ -f $1 ]
	then
		OUTPUT=$( awk "/^Package: $2$/{getline; print;}" $1 )
		if [ "$OUTPUT" = "Source: com.nokia.maemo/local" -o "$OUTPUT" = "Source: com.nokia.maemo" ]
		then
			return 0
		else
			return 1
		fi
	else
		return 2
	fi
}

RESTOK="/var/lib/aegis/restok/restok.conf"

fn_if_package_aegised $RESTOK "opensudo"
if [ $? = 0 ]
then 
	CMDPART="--sudo-mode -l"
else
	CMDPART="--ariadne-mode"
fi

COMMAND="Exec=invoker --type=d hmtsu $CMDPART -D /usr/share/applications/meego-terminal.desktop -- /usr/bin/meego-terminal -n"

sed "s,^Exec=.*,$COMMAND," /usr/share/applications/meego-root-terminal.desktop > /usr/share/applications/meego-root-terminal.tmp
mv /usr/share/applications/meego-root-terminal.tmp /usr/share/applications/meego-root-terminal.desktop

