#!/bin/sh

# $1 - restok.conf path
# $2 - package name
fn_if_package_aegised() {
	if [ -f $1 ]
	then
		OUTPUT=$( awk "/^Package: $2$/{getline; print;}" $1 )
		if [ "$OUTPUT" = "Source: com.nokia.maemo/local" -o "$OUTPUT" = "Source: com.nokia.maemo" ]
		then
			return 0
		else
			return 1
		fi
	else
		return 2
	fi
}

RESTOK="/var/lib/aegis/restok/restok.conf"

fn_if_package_aegised $RESTOK "khteditor"
if [ $? = 0 ]
then 
	echo "khteditor-rooted: khteditor is AEGISED"
	if [ -f "/usr/bin/ariadne" ]
	then
		CMDPART="--ariadne-mode"
	else
		fn_if_package_aegised $RESTOK "opensudo"
		if [ $? = 0 ]
		then 
			CMDPART="--sudo-mode -l"
		else
			CMDPART="--su-mode"
		fi
	fi
else
	echo "khteditor-rooted: khteditor is NOT aegised"
	CMDPART="--su-mode"
fi

COMMAND="Exec=invoker --type=d hmtsu $CMDPART -fD /usr/share/applications/khteditor.desktop"

sed "s,^Exec=.*,$COMMAND," /usr/share/applications/khteditor-rooted.desktop > /usr/share/applications/khteditor-rooted.tmp
mv /usr/share/applications/khteditor-rooted.tmp /usr/share/applications/khteditor-rooted.desktop

