#!/bin/sh

if [ -f "/usr/bin/ariadne" ]
then
	CMDPART="--ariadne-mode"
else
	CMDPART="--sudo-mode -l"
fi

COMMAND="Exec=invoker --type=d hmtsu $CMDPART -D /usr/share/applications/btinput-terminal.desktop -- /opt/btinput-terminal/bin/btinput-terminal -n"

sed "s,^Exec=.*,$COMMAND," /usr/share/applications/btinput-root-terminal.desktop > /usr/share/applications/btinput-root-terminal.tmp
mv /usr/share/applications/btinput-root-terminal.tmp /usr/share/applications/btinput-root-terminal.desktop

