#!/bin/sh

# $1 - restok.conf path
# $2 - package name
fn_if_package_aegised() {
	if [ -f $1 ]
	then
		OUTPUT=$( awk "/^Package: $2$/{getline; print;}" $1 )
		if [ "$OUTPUT" = "Source: com.nokia.maemo/local" -o "$OUTPUT" = "Source: com.nokia.maemo" ]
		then
			return 0
		else
			return 1
		fi
	else
		return 2
	fi
}

RESTOK="/var/lib/aegis/restok/restok.conf"

fn_if_package_aegised $RESTOK "txpadqml"
if [ $? = 0 ]
then 
	echo "txpadqml is AEGISED"
	if [ -f "/usr/bin/ariadne" ]
	then
		CMDPART="--ariadne-mode -- sh -c"
	else
		fn_if_package_aegised $RESTOK "opensudo"
		if [ $? = 0 ]
		then 
			CMDPART="--sudo-mode -l"
		else
			CMDPART="--su-mode"
		fi
	fi
else
	echo "txpadqml is NOT aegised"
	CMDPART="--su-mode"
fi

COMMAND="Exec=invoker --type=d hmtsu -D /usr/share/applications/txpad.desktop -V 2 $CMDPART 'export LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH:/opt/txpadqml/lib/\"; /opt/txpadqml/bin/txpad'"

sed "s,^Exec=.*,$COMMAND," /usr/share/applications/txpad-rooted.desktop > /usr/share/applications/txpad-rooted.tmp
mv /usr/share/applications/txpad-rooted.tmp /usr/share/applications/txpad-rooted.desktop

