#!/bin/sh

if [ -f "/usr/bin/ariadne" ]
then
	CMDPART="--ariadne-mode"
else
	CMDPART="--sudo-mode -l"
fi

COMMAND="Exec=invoker --type=d hmtsu $CMDPART -D /usr/share/applications/fingerterm.desktop /opt/fingerterm/bin/fingerterm"

sed "s,^Exec=.*,$COMMAND," /usr/share/applications/fingerterm-rooted.desktop > /usr/share/applications/fingerterm-rooted.tmp
mv /usr/share/applications/fingerterm-rooted.tmp /usr/share/applications/fingerterm-rooted.desktop

